### ISSUE TITLE
Photo frame gets stuck sometimes

### ISSUE THREAD

**Issue by pimterry** [pimterry/photo-frame#1]
```
12.11.17 19:34:28 (+0100) Cannot read property 'id' of undefined TypeError: Cannot read property 'id' of undefined
12.11.17 19:34:28 (+0100)     at /usr/src/app/data/random-fb-photos.jsx:81:45
12.11.17 19:34:28 (+0100)     at Generator.next (<anonymous>)
12.11.17 19:34:28 (+0100)     at step (/usr/src/app/data/random-fb-photos.jsx:1:284)
12.11.17 19:34:28 (+0100)     at /usr/src/app/data/random-fb-photos.jsx:1:530
12.11.17 19:34:28 (+0100)     at /usr/src/app/data/random-fb-photos.jsx:1:192
12.11.17 19:34:28 (+0100)     at RandomFbPhotos.loadImage (/usr/src/app/data/random-fb-photos.jsx:80:36)
12.11.17 19:34:28 (+0100)     at /usr/src/app/data/random-fb-photos.jsx:58:24
12.11.17 19:34:28 (+0100)     at Generator.next (<anonymous>)
12.11.17 19:34:28 (+0100)     at step (/usr/src/app/data/random-fb-photos.jsx:1:284)
12.11.17 19:34:28 (+0100)     at /usr/src/app/data/random-fb-photos.jsx:1:530
```

**Comment by pimterry** [comment]
Might be happening if one photo/one listing fails to load, so it gets stuck.
